Added fake error to yml

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -11,5 +11,10 @@ jobs:
          echo "Listing files in the repository(${{ github.workspace }}).."
          ls ${{ github.workspace }}
      - run: echo "Job's status is ${{ job.status }}"
+     - name: Faking an error
+       run: |
+         echo "Before faking an error"
+         exit 1
+         echo "After faking an error"
 
 
